### ISSUE TITLE
Cash previously held and already collected persist in Maintenance Panel when relogin

### ISSUE THREAD

**Issue by Eli-88** [limjohnny88/sqm_caws2#1]
Reset the values to empty for "Show Total Cash Held" and "Press to Collect Cash" when the Maintainer successfully pushes "Press Here When Finished"

![image](https://user-images.githubusercontent.com/25860086/44296680-e657c880-a2f5-11e8-94ee-c04c6fba0028.png)

Scenario:
Login
Collect all cash
Locked door and log out from the system
Login again to the system
Cash previously held is not cleared

**Comment by yguang004** [comment]
We will fix this bug when we implement the new feature.
This bug will take one day to fix.
These is no impact on current system

**Comment by jiangyumin** [comment]
![bugfix1](https://user-images.githubusercontent.com/1575992/44297209-2328bd00-a300-11e8-9070-5a578bdb0cd3.JPG)
Confirmed that the bug has been fixed.
Please refer to the test screenshot.
@pearljem Please verify.

**Comment by pearljem** [comment]
Verified that the fix worked.
Attached is
[TestResult VMCS_CR_1.docx](https://github.com/limjohnny88/sqm_caws2/files/2299250/TestResult.VMCS_CR_1.docx)
 the test result.

**Comment by limjohnny88** [comment]
Code have been merge and tag.
Tag: R1.0.9 
96da2ce4e35846a6ffd8709da12cf9bb82cfba7a
