### ISSUE TITLE
Enable an accounting check-and-balance that insures that what’s reported as collected by the machine is in fact what has been collected by the Maintainer

### ISSUE THREAD

**Issue by Eli-88** [limjohnny88/sqm_caws2#2]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This
will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash
Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

![image](https://user-images.githubusercontent.com/25860086/44296708-3d5d9d80-a2f6-11e8-9156-7d8bd775d252.png)

**Comment by yguang004** [comment]
This requirement will take 2 days to implements, 
These is no impact on current system.

**Comment by limjohnny88** [comment]
Feature have been implemented.
Please refer to commit: 9a0c4079bee04a002483a1824930b0536661c24c
@jiangyumin , please confirm that the feature have been implemented according to specs.

**Comment by jiangyumin** [comment]
![enhancement](https://user-images.githubusercontent.com/1575992/44297120-7994fc00-a2fe-11e8-88eb-de9a6ad62222.JPG)
Confirmed that the feature has been implemented. 
Please refer to the test screenshot.
@pearljem Please verify.

**Comment by pearljem** [comment]
Verified that enhancement is ok.
Attached is my test result.
[TestResult VMCS_CR_2.docx](https://github.com/limjohnny88/sqm_caws2/files/2299246/TestResult.VMCS_CR_2.docx)

**Comment by limjohnny88** [comment]
Code have been merge and tag.
Tag: R1.0.9 
96da2ce4e35846a6ffd8709da12cf9bb82cfba7a
